INSERT INTO Diseases VALUES ('Hypothyroidism','Facial expressions become dull');
INSERT INTO Diseases VALUES ('Hypothyroidism','Eyelids droop');
INSERT INTO Diseases VALUES ('Hypothyroidism','The eyes and face become puffy');
INSERT INTO Diseases VALUES ('Hypothyroidism','The skin becomes coarse, dry, scaly, and thick');
INSERT INTO Diseases VALUES ('Hypothyroidism','Weight Gain');
INSERT INTO Diseases VALUES ('Hyperthyroidism','Increased heart rate and blood pressure');
INSERT INTO Diseases VALUES ('Hyperthyroidism','Hand tremors');
INSERT INTO Diseases VALUES ('Hyperthyroidism','Nervousness and anxiety');
INSERT INTO Diseases VALUES ('Heart Attack','Pain in chest');
INSERT INTO Diseases VALUES ('Heart Attack','Faintness');
INSERT INTO Diseases VALUES ('Heart Attack','sudden heavy sweating');
INSERT INTO Diseases VALUES ('Heart Attack','nausea');
INSERT INTO Diseases VALUES ('Osteoarthritis','joint tenderness');
INSERT INTO Diseases VALUES ('Osteoarthritis','weakness and muscle wasting');
INSERT INTO Diseases VALUES ('Osteoarthritis','limited range of movement in joints');
INSERT INTO Diseases VALUES ('Osteoarthritis','a grating or crackling sound or sensation in joints');
INSERT INTO Diseases VALUES ('Conjunctivitis','eye redness');
INSERT INTO Diseases VALUES ('Conjunctivitis','a burning sensation in eyes');
INSERT INTO Diseases VALUES ('Conjunctivitis','a sticky coating on the eyelashes');